cart:
  fullnameOverride: carts

  serviceAccount:
    create: true
    name: carts

  app:
    persistence:
      provider: dynamodb
      dynamodb:
        tableName: project-bedrock-carts
        createTable: false

  dynamodb:
    create: false

catalog:
  fullnameOverride: catalog

  app:
    persistence:
      provider: mysql
      database: catalog
      secret:
        create: false
        name: catalog-db

  mysql:
    create: false

checkout:
  fullnameOverride: checkout

  app:
    persistence:
      provider: redis

    endpoints:
      orders: http://orders:80

  redis:
    create: true

orders:
  fullnameOverride: orders

  app:
    persistence:
      provider: postgres
      database: orders

      secret:
        create: false
        name: orders-db

    messaging:
      provider: rabbitmq

      rabbitmq:
        secret:
          create: false
          name: orders-rabbitmq

  postgresql:
    create: false

  rabbitmq:
    create: true

ui:
  fullnameOverride: ui

  replicaCount: 3

  app:
    endpoints:
      catalog: http://catalog:80
      carts: http://carts:80
      checkout: http://checkout:80
      orders: http://orders:80
